# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_user_is_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_level',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], max_length=8, null=True),
        ),
    ]
