# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20180416_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_level',
            field=models.CharField(blank=True, choices=[('level1', '1'), ('level2', '2'), ('level3', '3')], max_length=1, null=True, verbose_name='권한레벨'),
        ),
    ]
