# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20180416_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_level',
            field=models.IntegerField(blank=True, choices=[(1, '최고 권한'), (2, '일반 권한'), (3, '최하위 권한')], null=True, verbose_name='권한레벨'),
        ),
    ]
