# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 08:23
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('list_auth', models.IntegerField(blank=True, choices=[(1, '최고 권한'), (2, '일반 권한'), (3, '최하위 권한')], null=True, verbose_name='목록보기')),
                ('detail_auth', models.IntegerField(blank=True, choices=[(1, '최고 권한'), (2, '일반 권한'), (3, '최하위 권한')], null=True, verbose_name='상세보기')),
                ('writer_auth', models.IntegerField(blank=True, choices=[(1, '최고 권한'), (2, '일반 권한'), (3, '최하위 권한')], null=True, verbose_name='글쓰기')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='제목')),
                ('content', ckeditor.fields.RichTextField(verbose_name='내용')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='만든날짜')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notice.Notice_category', verbose_name='카테고리')),
            ],
        ),
    ]
