# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 07:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='제목')),
                ('text', djrichtextfield.models.RichTextField(default='', verbose_name='내용')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='만든날짜')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
                ('post_is_manager', models.BooleanField(default=False, verbose_name='관리자')),
                ('post_is_member', models.BooleanField(default=False, verbose_name='회원')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
