# Generated by Django 2.0 on 2018-04-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='분류을 선택하세요', on_delete=django.db.models.deletion.CASCADE, to='notice.Notice_category', verbose_name='카테고리'),
        ),
    ]
