# Generated by Django 2.0 on 2018-04-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20180416_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notice.Notice_category', verbose_name='카테고리'),
        ),
    ]
