# Generated by Django 2.0 on 2018-04-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
