# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20180417_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
