# Generated by Django 2.0 on 2018-04-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20180421_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word_filtering',
            name='post',
        ),
    ]
