# Generated by Django 2.0 on 2018-04-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_auto_20180421_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word_filtering',
            name='post',
        ),
    ]
