# Generated by Django 2.0 on 2018-04-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0009_remove_word_filtering_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='내용'),
        ),
    ]
