# Generated by Django 2.0 on 2018-04-21 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0010_auto_20180422_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='만든날짜')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.Post')),
            ],
        ),
    ]
