# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0014_auto_20180423_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imges',
            name='imges',
            field=models.ImageField(blank=True, null=True, upload_to='imges/%Y/%m/%d/'),
        ),
    ]
