# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0016_auto_20180424_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_category',
            name='detail_auth',
            field=models.IntegerField(blank=True, choices=[(1, 'manager 권한'), (2, 'family 권한'), (3, 'normal 권한')], null=True, verbose_name='상세보기'),
        ),
        migrations.AlterField(
            model_name='notice_category',
            name='list_auth',
            field=models.IntegerField(blank=True, choices=[(1, 'manager 권한'), (2, 'family 권한'), (3, 'normal 권한')], null=True, verbose_name='목록보기'),
        ),
        migrations.AlterField(
            model_name='notice_category',
            name='writer_auth',
            field=models.IntegerField(blank=True, choices=[(1, 'manager 권한'), (2, 'family 권한'), (3, 'normal 권한')], null=True, verbose_name='글쓰기'),
        ),
    ]
