# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0028_auto_20180509_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='imges',
            name='noimge',
            field=models.ImageField(default='static/img/noimg.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imges',
            name='imges',
            field=models.ImageField(blank=True, null=True, upload_to='imges/%Y/%m/%d/'),
        ),
    ]
