# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0029_auto_20180509_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imges_check',
            field=models.BooleanField(default=False),
        ),
    ]
