# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0031_remove_imges_noimge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imges_check',
        ),
        migrations.AddField(
            model_name='imges',
            name='imges_check',
            field=models.BooleanField(default=False),
        ),
    ]
